### ISSUE TITLE
Gabs will not parse an array at the top level

### ISSUE THREAD

**Issue by jaitaiwan** [Jeffail/gabs#10]
From (http://www.json.org):
> JSON is built on two structures:

> A collection of name/value pairs. In various languages, this is realized as an object, record, struct, dictionary, hash table, keyed list, or associative array.
> An ordered list of values. In most languages, this is realized as an array, vector, list, or sequence.

When passing an array into gabs:
```go
import (
    "github.com/jeffail/gabs"
    "fmt"
)

json, err := gabs.ParseJSON([]byte(`[]`))
fmt.Printf("%+v", err)
```
The `input text could not be parsed` error is generated. It seems to be because of this line in `func ParseJSON`:
```go
if _, ok := gabs.object.(map[string]interface{}); ok {
```

Whether or not that if statement is the only thing preventing parsing arrays, I'm not sure of but I think this is something that definitely needs resolving.

**Comment by jaitaiwan** [comment]
I took a more in-depth look at the code. It seems that it is definitely possible to have a top-level array with a bit of work. For now until I am able to make a pull request, or someone else fixes this, here's a work around that hacks around the issue for now:

```go
import (
    "github.com/jeffail/gabs"
    "fmt"
)

jsonObject := gabs.New()
jsonObject.SetP([]byte(`[{"name":"a"},{"name":"b"}]`)
children, _ := jsonObject.S("array").Children()
for _, v := range children {
    fmt.Log(v.StringIndent("", "    ")
}

/**
 * Prints
 * {
 *     "name" : "a"
 * },
 * {
 *     "name" : "b"
 * }
 */
```

**Comment by Jeffail** [comment]
Hey @jaitaiwan, if memory serves me this was simply because at one time gabs was unable to work with arrays, so an array at the root would be unusable in gabs. This isn't the case any more so you're right that this needs fixing. I can quickly add this in (probably tomorrow).

**Comment by Jeffail** [comment]
Hey @jaitaiwan,

https://github.com/Jeffail/gabs/commit/b69c9e648a2529c8d7b927ba7f87bc7fe0b3b0ea should fix this, gabs now allows any valid JSON value at the root, and you can manipulate the root value itself.

**Comment by jaitaiwan** [comment]
Thanks!
