### ISSUE TITLE
Invalid empty path JSONPointer handling

### ISSUE THREAD

**Issue by delaneyj** [Jeffail/gabs#100]
It appears per the spec `""` isn't being handled.  Empty string path is valid and is used with tools that merge json patches for example.
 
> To point to the root of the document use an empty string for the pointer. The pointer / doesn’t point to the root, it points to a key of "" on the root (which is totally valid in JSON).

https://github.com/Jeffail/gabs/blob/a650ef7728dcedb3072a735fdd0e38460e2286e8/gabs.go#L89-L91

**Comment by delaneyj** [comment]
In fact the `"/"` is also is broken as per spec `"/"` is a ref to the `""` key at the root (which is valid in JSON amazingly).

**Comment by Jeffail** [comment]
Whoops, thanks for raising this @delaneyj. Ironically, the only reason I added the JSONPointer methods in the first place was specifically to support referencing the key `{"":"foo"}` and also `{"":{"":"foo"}}`, which you can't do with the dot path notation, so the fact that these edge cases aren't even handled correctly is a bit embarrassing :sweat_smile:.

**Comment by Jeffail** [comment]
I believe this should be all we need: https://github.com/Jeffail/gabs/commit/280654410ea84ee0ef9a40fb73155233b66badf5, would appreciate if you could look it over and if you're happy I'll tag a patch release.

**Comment by Jeffail** [comment]
Tagged: https://github.com/Jeffail/gabs/releases/tag/v2.6.1
