### ISSUE TITLE
gabs.Container.Path() return null, even the value exists

### ISSUE THREAD

**Issue by x24870** [Jeffail/gabs#117]
I encountered a wired issue.
First, I start some goroutine then return the result by sending it to a channel.
Next use `gabs.Container.SetP()` to set these values to another gabs.Container.
When I try to get the value by `gabs.Container.Path()`, it returns null.
If you print the gabs.Container you can see the value exists, but can't access deeper level.

Not sure it's caused by transfer pointer through channel or `gabs.Container.Path()`.
Here is the code to reproduce it.
https://go.dev/play/p/MWIk0UT7p45

**Comment by mihaitodor** [comment]
Hey @x24870, thanks for reporting this issue! I think it's a duplicate of #98. Please see [this comment](https://github.com/Jeffail/gabs/issues/98#issuecomment-824059943) from Ash. Basically, you'll need to do `allRet.SetP(ret.Data(), strconv.Itoa(ret.Path("outter.inner.num").Data().(int)))` and it should work.

**Comment by x24870** [comment]
That works, many thanks!
