### ISSUE TITLE
Path/Search does not work with arrays

### ISSUE THREAD

**Issue by squillace91** [Jeffail/gabs#127]
The example given in the readme also does work. This is what I get when trying to run the example.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/1086713/196296772-6be456b5-18ef-482e-912c-641ebfd84b33.png">

**Comment by mihaitodor** [comment]
Are you using `github.com/Jeffail/gabs/v2`? It seems to work fine for me:

```go
package main

import (
	"github.com/Jeffail/gabs/v2"
)

func main() {
	jsonParsed, err := gabs.ParseJSON([]byte(`{"array":[{"value":1},{"value":2},{"value":3}]}`))
	if err != nil {
		panic(err)
	}
	val := jsonParsed.Path("array.1.value").String()
	if val != "2" {
		panic(val)
	}
}
```
