### ISSUE TITLE
Check existence

### ISSUE THREAD

**Issue by pjebs** [Jeffail/gabs#15]
This may be related to: https://github.com/Jeffail/gabs/issues/14

In your example: 

value, ok = jsonParsed.Search("outter", "inner", "value1").Data().(float64)
// value == 10.0, ok == true

value, ok = jsonParsed.Path("does.not.exist").Data().(float64)
// value == 0.0, ok == false

The second example is actually ambiguous.
`ok` could be false either because the path does not exist **OR** because the data could not be type asserted to float64.

Is there another way to just determine if the path exists -- irrespective of the data type or whether the type assertion failed.

**Comment by pjebs** [comment]
I haven't checked code but perhaps this is it:
`jsonParsed.Path("does.not.exist").Data() == nil`

**Comment by pjebs** [comment]
If the above code works, then maybe a nice convenience method: `jsonParsed.Path("does.not.exist").Exists()`

**Comment by Jeffail** [comment]
Hey @pjebs, your examples work but I've checked in `Exists()` to make things simpler. However, it is still faster to do a select on `.Data().(type)`, to save you the extra search.
