### ISSUE TITLE
Get methods

### ISSUE THREAD

**Issue by xogeny** [Jeffail/gabs#16]
Would you accept a pull request with some useful Get methods for specific types ala [`jason`](https://github.com/antonholmquist/jason)?

The point is that `gabs` seems to be good for building up data in `Container`s and `jason` seems to be good at reading values.  But it is useful to have both (in one package).  So I would propose adding basically the same methods `Get*` that `jason` has.

Comments?

**Comment by Jeffail** [comment]
Hey @xogeny, after a lot of thought I've decided to leave the API as it is for now. I'd rather encourage users to stick to the native go way of `v, ok := gabs.Data().(string)` rather than add a `gabs.String()` method, since it also encourages users to opt for type select statements etc.
