### ISSUE TITLE
something wrong with ints

### ISSUE THREAD

**Issue by pjebs** [Jeffail/gabs#17]
I am sending this in an request to my golang app:

`{"id":2027907052821425841}`

Goapp app:
`_id, ok_1 := reqJson.Path("id").Data().(float64)`
`id := uint64(_id)`

I am adding `id` to my database and it ends up being:`2027907052821425920`.

What is going on here?

It should be `2027907052821425841` so now my database is inconsistent. The database field is set up to `unsigned bigint` which ranges from `[0,   18446744073709551615]`

**Comment by pjebs** [comment]
My end solution was to force the input to be wrapped as a string and use the `strconv` package.
Not ideal.

Perhaps your library can allow us to hint that we expect the number to be of a certain int type, and you then manually bypass the go json parser and first wrap it as a string and then run strconv automatically

**Comment by pjebs** [comment]
https://github.com/Jeffail/gabs/issues/12

**Comment by pjebs** [comment]
Any thoughts on this workaround?

**Comment by Jeffail** [comment]
Hey @pjebs, sorry for the late response. Using `json.NewDecoder` with `.UseNumber()` is definitely the right solution here. Currently you'd need to do the following:

```go
    d := json.NewDecoder(strings.NewReader(`{"data":"test"}`))
    d.UseNumber()
    if err := d.Decode(&result); err != nil {
        panic(err)
    }

    g, err := gabs.Consume(result)
    if err != nil {
        panic(err)
    }
```
But I'm going to merge https://github.com/Jeffail/gabs/pull/22 since that shortens it to the following:

```go
sample := []byte(`{"test":{"int":10, "float":6.66}}`)
dec := json.NewDecoder(bytes.NewReader(sample))
dec.UseNumber()

val, err := ParseJSONDecoder(dec)
if err != nil {
	t.Errorf("Failed to parse: %v", err)
	return
}

intValue, err := sample.Path("test.int").Data().(json.Number).Int64()
```

**Comment by pjebs** [comment]
I'll wait for the merge

**Comment by Jeffail** [comment]
Merged now, also stuck a section into the README that explains it
