### ISSUE TITLE
Outer array?

### ISSUE THREAD

**Issue by k2xl** [Jeffail/gabs#19]
Can you provide examples of how to access values when top level json is an array?

i.e.
```
[{"hello":"friend"},{"good":"morning"}]
```
Maybe it'd be nice to be able to get a slice of jsonParsed? Or Be able to search via index like "0.hello"?

**Comment by Jeffail** [comment]
Hey @k2xl, to access a particular index you can use `jsonParsed.Index(i)`, so for your example of "0.hello" you would need `jsonParsed.Index(0).S("hello")`.

You can also iterate the elements in an array by accessing a slice of the children with `jsonParsed.Children()`.

**Comment by bonafideyan** [comment]
It does not work.

        ```
jsonobj := gabs.New()
	jsonobj.Array()
	jsonobj1 := gabs.New()
	jsonobj1.SetP(1324, "a.b.c")
	jsonobj.ArrayAppend(jsonobj1)
	c, err := jsonobj.ArrayCount()
	if err != nil {
		t.Error(err)
	}
	println(c)
	s, err := jsonobj.MarshalJSON()
	if err != nil {
		t.Error(err)
	}
	println(string(s))
	dd := jsonobj.Index(0)
	v, ok := dd.Path("a.b.c").Data().(int)
	if !ok {
		t.Error(ok)
	}
	fmt.Printf("%T,%v", v, v)
	println(v)
```
