### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by careuno** [Jeffail/gabs#2]
I am not able to work with gabs. It always throws  this panic error. That's my code:

	response, err := http.Get(uri)
	if err != nil {
		return nil, nil, err
	}
	defer response.Body.Close()
	contents, err := ioutil.ReadAll(response.Body)
	fmt.Println(string(contents))
	jsonParsed, err := gabs.ParseJSON(contents)
........

**Comment by Jeffail** [comment]
Hey, any hints as to what the contents are when this happens?

**Comment by Jeffail** [comment]
I've tried to reproduce this issue, and added some auto tests for parsing invalid JSON blobs, and found nothing unexpected thus far. If you can give me some more info then I'm happy to continue looking at this, otherwise I'm going to close the issue after a week.

**Comment by PaladinTyrion** [comment]
@careuno， maybe U can check your console log，find what has been printed to determine where the issue happens. And can U paste your log here?

**Comment by PaladinTyrion** [comment]
@Jeffail , I love your wapping about tunny & gabs, especially tunny. I love them so much and have use them. Your coding style guides me. I wanna thank you and  I will star more project from you.
Thank you ！！！！！

**Comment by careuno** [comment]
Hi sorry for the delay. I couldn't find the problem and used another soluction but I think the problem went from different issue. Trying gabs in different project, it worked perfectly.

**Comment by Jeffail** [comment]
Hey, no problem, I'll close the issue then.
