### ISSUE TITLE
Delete an element from an array

### ISSUE THREAD

**Issue by k0pernicus** [Jeffail/gabs#25]
Hi!  
Nice work for this lib' 👍 

I'm dealing to remove an element from an array.  
I used `Delete`, but this method deals only with objects.

Is a method exists for my problem, because I don't see how to make this happen easily...?

Thanks a lot!

**Comment by Jeffail** [comment]
Hey @k0pernicus, take a look at https://github.com/Jeffail/gabs/blob/master/gabs.go#L387, `ArrayRemove(index int, path ...string) error` should remove a specific element from an array at `path`.

**Comment by k0pernicus** [comment]
Hi @Jeffail !

Thanks for this answer.
One of my idea was to use `ArrayRemove` indeed - but is a method exists to get an index of an Array, without iterating "manually" on the data structure?

Thanks again!

**Comment by Jeffail** [comment]
You mean with something like `IndexOf`? If so then not currently, you'd have to write it yourself.

**Comment by k0pernicus** [comment]
Ok great, thanks again :-)
