### ISSUE TITLE
Nested Container

### ISSUE THREAD

**Issue by JamesCullum** [Jeffail/gabs#27]
I have the functions A & B that generate different parameters as JSON. I give this container to a function C, which creates a new container and should use the result from A/B as parameter. This appears to be currently not possible (setting a container creates an empty key-pair).

Example code

```
func finalize(method string, params *gabs.Container) (*gabs.Container, error) {
	reqMap := gabs.New()
	reqMap.Set("val", "name")
	if params != nil {
		fmt.Println("Append: ", params.String())
		reqMap.Set(params, "params")
	}
	fmt.Println(reqMap.String());
}
```

Another use case is for example if i want to generate an array out of objects. I could then just append the objects via ArrayAppend.

**Comment by JamesCullum** [comment]
Found a solution by looking at the code: It is easily possible to nest them, one just needs to use .Data() before. The working example is

```
func finalize(method string, params *gabs.Container) (*gabs.Container, error) {
    reqMap := gabs.New()
    reqMap.Set("val", "name")
    if params != nil {
        fmt.Println("Append: ", params.String())
        reqMap.Set(params.Data(), "params")
    }
    fmt.Println(reqMap.String());
}
```

Adding nested containers to the readme may be a good idea though :+1:

**Comment by jan4984** [comment]
this should be documented, it takes me much time for searching solution

**Comment by andrewpmartinez** [comment]
This just hit me too.

Also it should be easy enough during the processing to assert the type and call .Data() for the outside code.
