### ISSUE TITLE
Generate array in array

### ISSUE THREAD

**Issue by korpa** [Jeffail/gabs#3]
Hi @Jeffail,

Thank you very much for this nice package.

Is there an easier way to achieve following json:

```
{
  "columns": [
    [
      "a",
      "1"
    ],
    [
      "a",
      "2"
    ],
    [
      "b",
      "1"
    ],
    [
      "b",
      "2"
    ]
  ]
}
```

Is there an easier way than this "dummy" workaround?

```
package main

import (
	"fmt"
	"github.com/jeffail/gabs"
)

func main() {

	letters := []string{"a", "b"}
	numbers := []string{"1", "2"}

	outerArray := gabs.New()
	outerArray.Array("columns")

	for _, letter := range letters {
		for _, number := range numbers {

			innerArray := gabs.New()
			innerArray.Array("dummy")
			innerArray.ArrayAppend(letter, "dummy")
			innerArray.ArrayAppend(number, "dummy")

			outerArray.ArrayAppend(innerArray.Path("dummy").Data(), "columns")
		}
	}
	fmt.Println(outerArray.StringIndent("", "  "))
}
```

Thanks

**Comment by Jeffail** [comment]
Hey @korpa,

For anonymous arrays it looks like your solution is currently the correct one. This seems convoluted so I'll look into improving the support for arrays, what we really need here is the ability to identify and mutate json objects by array index rather than just path, and specifying a predetermined size of an array as we create it.

I'll get back to you on this.

Cheers

**Comment by korpa** [comment]
Thank you very much for your answer. Then I leave it for now as it is and will change it later when a solution is available.

**Comment by Jeffail** [comment]
Hey @korpa,

I've added some goodies for working with arrays. Your example can now be done with:

```go
package main

import (
    "fmt"
    "github.com/jeffail/gabs"
)

func main() {

    letters := []string{"a", "b"}
    numbers := []string{"1", "2"}

    outerArray := gabs.New()
    outerArray.ArrayOfSize(len(letters)*len(numbers), "columns")

    for i, letter := range letters {
        for j, number := range numbers {
            tmpArray, _ := outerArray.S("columns").ArrayOfSizeI(2, i*2+j)
            tmpArray.SetIndex(letter, 0)
            tmpArray.SetIndex(number, 1)
        }                    
    }                        

    fmt.Println(outerArray.StringIndent("", "  "))
}
```

**Comment by korpa** [comment]
This works like a charm, too. The only downside of this is that you need an index variable. If I this in combination with childrenMap() of #4 there is no index variable. Therefore I have to define ```var i int``` and do a ```i++``` within the range routine.
Nevertheless #3 and #4 helped me to cut the code in half. Thank you very much.
