### ISSUE TITLE
Json structure - equivalent gabs commands

### ISSUE THREAD

**Issue by the42** [Jeffail/gabs#32]
Supposed I have the given JSON structure:

    {
       "name" : "external",
       "children" : [
          {
             "size" : 1,
             "name" : "WikiLeaks"
          },
          {
             "name" : "PanamaLeaks",
             "size" : 1
          },
          {
             "name" : "internal",
             "children" : [
                {
                   "children" : [
                      {
                         "size" : 1,
                         "name" : "ZPR"
                      },
                      {
                         "size" : 1,
                         "name" : "ZMR"
                      }
                   ],
                   "name" : "bmi"
                },
                {
                   "name" : "bmeia",
                   "children" : [
                      {
                         "name" : "AWO",
                         "size" : 1
                      },
                      {
                         "size" : 1,
                         "name" : "AWD"
                      }
                   ]
                },
                {
                   "name" : "bmf",
                   "children" : [
                      {
                         "children" : [
                            {
                               "name" : "GU",
                               "size" : 1
                            },
                            {
                               "name" : "FGH",
                               "size" : 1
                            }
                         ],
                         "name" : "core"
                      }
                   ]
                }
             ]
          }
       ]
    }

How do the corresponding Gabs-Commands look like?

**Comment by hssg44** [comment]
Firend,I have a JSON be like to U

**Comment by sairam** [comment]
this json looks like this part of a menu item or a structured entity. You'd need to loop through the 1st set of "children" nodes and match the name and loop through their children. 

Your json looks like it can fit in a struct since its structured.

**Comment by Majonsi** [comment]
No you don't have to change your structure!

please see [here](https://github.com/Jeffail/gabs/issues/34).
