### ISSUE TITLE
unable to get go get github.com/Jeffail/gabs

### ISSUE THREAD

**Issue by Rajkumrjsn** [Jeffail/gabs#38]
# github.com/Jeffail/gabs
../go/src/github.com/Jeffail/gabs/gabs.go:429: e.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)
../go/src/github.com/Jeffail/gabs/gabs.go:436: e.SetIndent undefined (type *json.Encoder has no field or method SetIndent)
../go/src/github.com/Jeffail/gabs/gabs.go:447: encoder.SetEscapeHTML undefined (type *json.Encoder has no field or method SetEscapeHTML)

**Comment by Jeffail** [comment]
Hey @Rajkumrjsn, I can pull it fine on my machine. Which version of Go are you building with?

**Comment by pjebs** [comment]
I noticed that `/jeffail` got changed to `/Jeffail` which is breaking all my package imports.
When did this happen?

**Comment by cliffano** [comment]
@Jeffail It failed only on golang 1.6 for me. Fine on 1.7 all the way to tip.

**Comment by KinoLien** [comment]
Version 1.2.1 failed too, maybe these methods exist on version >= 1.7 ?

**Comment by pjebs** [comment]
Go Dep: `dep init` produces these results when I run `dep init` on a project with old dependency:
```
...
safe write of manifest and lock: error while writing out vendor tree: failed to write dep tree: failed to export github.com/jeffail/gabs: : exit status 128
```

These discussions all say it's due to case-sensitive changes to repo name:
https://github.com/golang/dep/issues/1072
https://github.com/golang/dep/issues/797
https://github.com/golang/dep/issues/1199

**Comment by Jeffail** [comment]
Hey @pjebs I think unfortunately you're forced at this stage to rewrite the imports as Jeffail/gabs. I've had to rewrite them already in most of my projects since I used to prefer the lowercase but came across similar issues that seemed to never end.
