### ISSUE TITLE
keys get lost

### ISSUE THREAD

**Issue by korpa** [Jeffail/gabs#4]
Hi @Jeffail,

I have another question. Have a look at following program:

```
package main

import (
	"fmt"

	"github.com/jeffail/gabs"
)

func main() {

	json, _ := gabs.ParseJSON([]byte(`{
		"data" : {
			"x1" : {
				"a" : 1,
				"b" : 2,
				"c" : 3
			},
			"x2" : {
				"a" : 4,
				"b" : 5,
				"c" : 6
			}
		}
	}`))
	x, _ := json.Path("data").Children()
	for xKey, xValue := range x {
		fmt.Println(xKey, " - ", xValue)
	}
}
```

The response is:
```
0  -  {"a":1,"b":2,"c":3}
1  -  {"a":4,"b":5,"c":6}
```

You see, the keys "x1" and "x2" get lost. 

Now I use following workaround
```
x, _ = json.Path("data").Data().(map[string]interface{})
```
to get the keys and iterate through them. But then I have to use following within the range:

```
a := json.Path("data."+xKey+".a").Data().(float64)
b := json.Path("data."+xKey+".b").Data().(float64)
c := json.Path("data."+xKey+".c").Data().(float64)
```
This works but could be nicer if Children() would return the keys if using with a json object. Or do you have another solution for this?

Thank you very much

**Comment by Jeffail** [comment]
Great point, there's no technical reason why we can't return a map[string]*gabs.Container here to do what you need. I'll have to add a new function, perhaps something like `ChildrenMap()`, to make this a non-breaking addition.

**Comment by Jeffail** [comment]
Hey @korpa,

I've added a method `ChildrenMap` which returns a `map[string]*gabs.Container`, and this should give you the field keys as well as the values.

**Comment by korpa** [comment]
Thank you very much. Works like a charm.
