### ISSUE TITLE
Merge that allow to replace instead of generating an array.

### ISSUE THREAD

**Issue by marcgauthier** [Jeffail/gabs#40]
Here a small change I would like to submit for review:

Adding a replace bool in the Merge function to allow to replace an object instead of creating an array.

// Merge - Merges two gabs-containers
func (g *Container) Merge(toMerge *Container, replace bool) error {
    var recursiveFnc func(map[string]interface{}, []string) error
    recursiveFnc = func(mmap map[string]interface{}, path []string) error {
        for key, value := range mmap {
            newPath := append(path, key)
            if !replace && g.Exists(newPath...) {
                target := g.Search(newPath...)
                switch t := value.(type) {
                case map[string]interface{}:
                    switch targetV := target.Data().(type) {
                    case map[string]interface{}:
                        if err := recursiveFnc(t, newPath); err != nil {
                            return err
                        }
                    case []interface{}:
                        g.Set(append(targetV, t), newPath...)
                    default:
                        newSlice := append([]interface{}{}, targetV)
                        g.Set(append(newSlice, t), newPath...)
                    }
                case []interface{}:
                    for _, valueOfSlice := range t {
                        if err := g.ArrayAppend(valueOfSlice, newPath...); err != nil {
                            return err
                        }
                    }
                default:
                    switch targetV := target.Data().(type) {
                    case []interface{}:
                        g.Set(append(targetV, t), newPath...)
                    default:
                        newSlice := append([]interface{}{}, targetV)
                        g.Set(append(newSlice, t), newPath...)
                    }
                }
            } else {
                // path doesn't exist. So set the value
                if _, err := g.Set(value, newPath...); err != nil {
                    return err
                }
            }
        }
        return nil
    }
    if mmap, ok := toMerge.Data().(map[string]interface{}); ok {
        return recursiveFnc(mmap, []string{})
    }
    return nil
}

**Comment by Jeffail** [comment]
Hey @marcgauthier, I meant to come back to this issue sooner. I'll take a look at adding this soon.

**Comment by Jeffail** [comment]
Hey @marcgauthier, I've added a function [`MergeFn`](https://godoc.org/github.com/Jeffail/gabs#Container.MergeFn) that allows you to specify your own collision behaviour rather than needing to copy/paste the whole `Merge` function.
