### ISSUE TITLE
SetP to update arrays

### ISSUE THREAD

**Issue by francoispqt** [Jeffail/gabs#49]
Hi,

Does the `SetP` method allow to update an array? 
Something like: 
```
c.SetP(1, "prop.array.$1")
```
If yes, what is the syntax for a path to an array index? 

Thank you

**Comment by Jeffail** [comment]
Hey @francoispqt, use https://godoc.org/github.com/Jeffail/gabs#Container.SetIndex, like this:

``` go
c.Path("prop.array").SetIndex("foo", 1)
```

**Comment by francoispqt** [comment]
Oh yes didn't think about it, thanks!
