### ISSUE TITLE
Deleting from a json

### ISSUE THREAD

**Issue by juandiegopalomino** [Jeffail/gabs#5]
Hi Jeffail,
Firstly, thank you for writing this library. It saved my teammates and I a lot of trouble with dealing with maps. I was wondering if there are any plans of supporting deletes (e.g. delete a field withing a container given a path).

**Comment by Jeffail** [comment]
Hey @juandiegopalomino,
I'm actually surprised that I overlooked this. I've just pushed this in: `g.Delete("path", "to", "element")`
Hope this helps!

**Comment by juandiegopalomino** [comment]
Thank you Jeffail! I'll check it out later today!
