### ISSUE TITLE
Generating arrays with recursion

### ISSUE THREAD

**Issue by shellkjell** [Jeffail/gabs#53]
Currently, I didn't find a way to generate an array with this case of recursion:
I have a structure which is parsed and then being interpreted in a function as a value to set in a container.

Consider the following code
```
type DataObject struct {
	Value  *string
	Values []*DataObject
}

func toJSON(data *DataObject, rootName string, currContaier, root *gabs.Container) {
	if data.Values != nil {
		newContainer, _ := currContaier.Array(rootName)
		for i, val := range data.Values {
			toJSON(val, "", newContainer, root)
		}
	} else { // data.Value != nil, always true here
		currContaier.ArrayAppend(data.Value, "") // WRONG, obviously
	}
}
```

Is there any way to do this without having the function itself being aware of the index in the array I'm trying to build?

**Comment by Jeffail** [comment]
Hey @shellkjell in this case it's probably easier to pass the value of the current array as a `[]interface{}` type, append all your values using the native `append` function, then set its value within the original structure at the end.
