### ISSUE TITLE
jsonpath support

### ISSUE THREAD

**Issue by sanqingshan** [Jeffail/gabs#54]
I think it will be perfect if support for jsonpath

**Comment by Jeffail** [comment]
Hey @sanqingshan, I have an implementation of JSON Pointer already https://godoc.org/github.com/Jeffail/gabs#Container.JSONPointer which looks like this: `/foo/bar/0/baz`. My plan is to also resolve explicit indexes for array fields in both the `Search` and `Path` functions in a new major version of Gabs.

I'm not currently planning on implementing any support for scripting within the path syntax's of any of these functions right now.
