### ISSUE TITLE
any way to sort the json array based upon time

### ISSUE THREAD

**Issue by aqsyonas** [Jeffail/gabs#62]
I have a JSON array like below and would like to sort this based upon the time feild. 

```
[
  {
    "create_date": "2019-08-28T07:01:10.000382-04:00",
    "data_header": {
      "callid": "first@127.0.0.1"
    }
  },
  {
    "create_date": "2019-08-28T07:01:30.000631-04:00",
    "data_header": {
      "callid": "third@127.0.0.1",
      
    }
  },
  {
    "create_date": "2019-08-28T07:01:20.000631-04:00",
    "data_header": {
      "callid": "second@127.0.0.1",
      
    }
  }
]
```

So, the result should like this below. 

```
[
  {
    "create_date": "2019-08-28T07:01:10.000382-04:00",
    "data_header": {
      "callid": "first@127.0.0.1"
    }
  },
  {
    "create_date": "2019-08-28T07:01:20.000631-04:00",
    "data_header": {
      "callid": "second@127.0.0.1",
      
    }
  },
  {
    "create_date": "2019-08-28T07:01:30.000631-04:00",
    "data_header": {
      "callid": "third@127.0.0.1",
      
    }
  }
]
```

Any suggestion would be much appreciated. Thanks.

**Comment by Jeffail** [comment]
Hey @aqsyonas, for that purpose I would extract the array using `foo.S("bar").Data().([]interface{})`, perform the sort using https://golang.org/pkg/sort/#Slice using gabs queries with something like:

```go
sort.Slice(vals, func(i, j int) bool {
  return gabs.Wrap(vals[i]).S("data_header", "callid").Data().(string) < gabs.Wrap(vals[j]).S("data_header", "callid").Data().(string)
})
```

^ Use this snippet with caution I haven't actually tested it at all.

**Comment by aqsyonas** [comment]
@Jeffail Thanks for your help. There is what I have tried 
[https://play.golang.org/p/dbdxZVBvCa4](url) 
but this is not working for me. 

Thank you for always supporting.

**Comment by Jeffail** [comment]
The JSON was malformed: https://play.golang.org/p/NSN-vsZs_oQ

**Comment by aqsyonas** [comment]
Ahh. Really sorry about malformed json. Your example did work for me. Thank you very much. :)
