### ISSUE TITLE
the "Iterating arrays" test case in README cannot work

### ISSUE THREAD

**Issue by zhilongliu** [Jeffail/gabs#69]
the test case in README:
jsonParsed, err := gabs.ParseJSON([]byte(`{"array":["first","second","third"]}`))
if err != nil {
	panic(err)
}

for _, child := range jsonParsed.S("array").Children() {
	fmt.Println(child.Data().(string))
}

compiler complained that "multiple-value jsonParsed.S("array").Children() in single-value context"

I cannot fix it after I tries several times...

**Comment by zhilongliu** [comment]
@Jeffail excuse me for the PING comment.

**Comment by Jeffail** [comment]
Hey @zhilongliu, the example in the README is for gabs v2, which if you're using modules then you need to import with:

```go
import "github.com/Jeffail/gabs/v2"
```

Otherwise you'll pull the old version which has the function signature `Children() ([]*Container, error)`, which is why you get the "multiple-value" error.

**Comment by zhilongliu** [comment]
thanks very much.
