### ISSUE TITLE
Feature Request: Work with streams

### ISSUE THREAD

**Issue by jaitaiwan** [Jeffail/gabs#7]
In go's http responses, the Body is provided as an io.ReadCloser data type. It would be great if it were possible to pass that directly into gabs without loading the entire json into memory.

I took an initial look at the code and couldn't see anything helpful so I'll do my best to see if I can provide a PR even with my little go experience.

**Comment by philipgiuliani** [comment]
This would be great! :)

**Comment by jaitaiwan** [comment]
@Jeffail I've added a pull request for this issue. Am hoping my noobish Golang ways aren't getting in the way of a nice-to-have feature :)
