### ISSUE TITLE
"Iterating arrays" example fails

### ISSUE THREAD

**Issue by stephan57160** [Jeffail/gabs#81]
Copy/Paste in go playground & "run" gives the following:
```
go: finding module for package github.com/Jeffail/gabs
go: downloading github.com/Jeffail/gabs v1.4.0
go: found github.com/Jeffail/gabs in github.com/Jeffail/gabs v1.4.0
./prog.go:14:54: multiple-value jsonParsed.S("array").Children() in single-value context

```
Code example available here :
https://play.golang.org/p/ut1D_Y6jh1P

**Comment by Jeffail** [comment]
Hey @stephan57160, it's importing the V1 API, make sure the import has the v2 suffix: `import "github.com/Jeffail/gabs/v2"`
