### ISSUE TITLE
"Iterating objects" example fails

### ISSUE THREAD

**Issue by Chinta** [Jeffail/gabs#87]
Copy/Paste in go playground & "run" gives the following:
```
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
main.main()
	/tmp/sandbox698136282/prog.go:16 +0x2cd
```

Code example available here:
https://play.golang.org/p/Kto3AqMUAXm

**Comment by Jeffail** [comment]
Hey @Chinta, that is definitely a bug in the example code. Thanks for raising this.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/gabs/commit/e47bd8079aa6dcc9e48a4035f3f1714b54dc2dcd
