### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by geoynomous** [Jeffail/gabs#96]
Getting `fatal error: concurrent map writes` when calling `SetP` (from gabs.go:306)

Is there a chance go use locks or a syncmap (see https://stackoverflow.com/questions/45585589/golang-fatal-error-concurrent-map-read-and-map-write/45585833) - maybe optional?

**Comment by geoynomous** [comment]
and another similar from line 784

**Comment by Jeffail** [comment]
Hey @geoynomous, there's no support within gabs for concurrent use, if you want to share a gabs container across multiple goroutines then you'll need to protect it with a mutex.
